name: Deploy PyMakr

on:
  # the 1st condition
  workflow_run:
    workflows: [test]
    # branches: [main, master, beta] disable while we test it
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci

      - name: Publish
        run: npm run semantic-release -- --dry-run --debug
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}