name: Deploy PyMakr

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: vsce-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci

      - name: Publish
        # for testing, add -- --dry-run --debug
        run: npm run semantic-release
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN2 }}
          # Personal token. Has access to merge commits (for changelog.md and package.json versioning)
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Repo token. Can create a new release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}