name: Deploy PyMakr

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: vsce-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci

      - name: Publish
        # for testing, add -- --dry-run --debug
        run: npm run semantic-release
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}
          GH_TOKEN: ${{ secrets.JAKOB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}