name: Test > Deploy PyMakr

on:
  push:
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: vsce-publish    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci

    - if: runner.os == 'Linux'
      name: Run tests (Linux)
      run: |
        rm /home/runner/work/pymakr-vsc/pymakr-vsc/node_modules/@serialport/bindings/build/Release/bindings.node
        xvfb-run -a npm test

    - if: runner.os != 'Linux'
      name: Run tests (Mac/Win)
      run: npm test
    
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}
